version: 0.2
phases:
 install:
   commands:
     - npm i -g npm-cli-login
     - npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL
     - npm i -g @eximchain/dappsmith create-react-app
 build:
   commands:
    - dappsmith --config config.json --dir dapp --build
artifacts:
  name: BUILD
  base-directory: dapp/build
  files:
    - '**/*'