version: 0.2
phases:
 install:
   commands:
     - echo "--- BEGINNING INSTALLATION ---"
     - echo "  - Installing npm-login-cli..."
     - npm i -g npm-cli-login
     - echo "  - npm-cli-login installed.  Logging in..."
     - npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL
     - echo "  - Login successful.  Installing dappsmith & create-react-app..."
     - npm i -g @eximchain/dappsmith create-react-app
 build:
   commands:
    - echo "--- BEGINNING BUILD ---"
    - dappsmith --config config.json --dir dapp
    - pwd
    - ls -a
    - echo "Initial generation successful.  Entering and installing..."
    - cd dapp
    - npm install
    - echo "Installation complete.  Building..."
    - npm run build
    - echo "Build complete.  Zipping..."
    - zip -r ../build.zip build/
artifacts:
  name: BUILD
  files:
    - build.zip